// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBbZML75hkHV7L9K8gfr4Ic-t8WmUWC8g',
    appId: '1:452960630161:web:42c2e3083c92badebe1630',
    messagingSenderId: '452960630161',
    projectId: 'water-reminder-app-eb171',
    authDomain: 'water-reminder-app-eb171.firebaseapp.com',
    storageBucket: 'water-reminder-app-eb171.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgRusZtnqEH6m7EaZSvBsDDLrw3cwjm0A',
    appId: '1:452960630161:android:523916bc6bd4f4e1be1630',
    messagingSenderId: '452960630161',
    projectId: 'water-reminder-app-eb171',
    storageBucket: 'water-reminder-app-eb171.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjhWw-XaBycVvRIqvlG5cFpL32yHIemlo',
    appId: '1:452960630161:ios:c04199e221312fcfbe1630',
    messagingSenderId: '452960630161',
    projectId: 'water-reminder-app-eb171',
    storageBucket: 'water-reminder-app-eb171.appspot.com',
    iosClientId: '452960630161-fj07q5729853ie5ut879q2s7dbkldshi.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjhWw-XaBycVvRIqvlG5cFpL32yHIemlo',
    appId: '1:452960630161:ios:c04199e221312fcfbe1630',
    messagingSenderId: '452960630161',
    projectId: 'water-reminder-app-eb171',
    storageBucket: 'water-reminder-app-eb171.appspot.com',
    iosClientId: '452960630161-fj07q5729853ie5ut879q2s7dbkldshi.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterApp',
  );
}
